# Generated by Django 3.1.7 on 2021-05-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='warden',
        ),
    ]
