# Generated by Django 3.1.7 on 2021-05-15 05:45

from django.db import migrations, models
import django.db.models.deletion
import loginapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20210504_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('roll_no', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[loginapp.models.valid_email])),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=255)),
                ('Course', models.CharField(choices=[('copc', 'COPC'), ('cose', 'COSE'), ('enc', 'ENC'), ('coe', 'COE'), ('ele', 'ELE'), ('ece', 'ECE'), ('mec', 'MEC'), ('che', 'CHE')], default='COPC', max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
            options={
                'db_table': 'STUDENT',
            },
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=255, unique=True, validators=[loginapp.models.valid_email])),
                ('date_of_entry', models.DateField()),
                ('time_of_entry', models.TimeField()),
                ('warden_name', models.CharField(max_length=256)),
                ('warden_email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Record_Table',
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loginapp.customuser')),
            ],
        ),
    ]
