# Generated by Django 3.1.7 on 2021-05-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20210518_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last-login'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='warden_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loginapp.user'),
        ),
    ]
